# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/design_1_spatial_audio_top_0_0.xci
# IP: The module: 'design_1_spatial_audio_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_audio || ORIG_REF_NAME==clk_wiz_audio} -quiet] -quiet

# IP: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_left/rom_hrtf_left.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hrtf_left || ORIG_REF_NAME==rom_hrtf_left} -quiet] -quiet

# IP: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hrtf_right || ORIG_REF_NAME==rom_hrtf_right} -quiet] -quiet

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_audio || ORIG_REF_NAME==clk_wiz_audio} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_audio || ORIG_REF_NAME==clk_wiz_audio} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_ooc.xdc

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_left/rom_hrtf_left_ooc.xdc

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right_ooc.xdc

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Src/Constraint/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_spatial_audio_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/design_1_spatial_audio_top_0_0.xci
# IP: The module: 'design_1_spatial_audio_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_audio || ORIG_REF_NAME==clk_wiz_audio} -quiet] -quiet

# IP: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_left/rom_hrtf_left.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hrtf_left || ORIG_REF_NAME==rom_hrtf_left} -quiet] -quiet

# IP: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom_hrtf_right || ORIG_REF_NAME==rom_hrtf_right} -quiet] -quiet

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_audio || ORIG_REF_NAME==clk_wiz_audio} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_audio || ORIG_REF_NAME==clk_wiz_audio} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_ooc.xdc

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_left/rom_hrtf_left_ooc.xdc

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Vivado_WorkDir/spatial_audio.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right_ooc.xdc

# XDC: d:/Vivado_Projects/ECE532_SpatialAudio/ECE532_SpatialAudio.srcs/sources_1/bd/design_1/ip/design_1_spatial_audio_top_0_0/Src/Constraint/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_spatial_audio_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
