# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right.xci
# IP: The module: 'rom_hrtf_right' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_hrtf_right'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right.xci
# IP: The module: 'rom_hrtf_right' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/rom_hrtf_right/rom_hrtf_right_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_hrtf_right'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
