# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xci
# IP: The module: 'clk_wiz_audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xci
# IP: The module: 'clk_wiz_audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/ECE532/532_spatial_test/spacial_test_proj/spacial_test_proj.srcs/sources_1/ip/clk_wiz_audio/clk_wiz_audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
