# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1.xci
# IP: The module: 'design_gyro_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gyro_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gyro_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gyro_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1.xci
# IP: The module: 'design_gyro_microblaze_0_axi_intc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gyro_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gyro_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_gyro_microblaze_0_axi_intc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
