# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.cache/wt [current_project]
set_property parent.project_path C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths c:/Users/eliza/Documents/1_Local/ECE532_local/vivado-library-master [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/hdl/design_gyro_wrapper.v
add_files C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/design_gyro.bd
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/design_gyro_PmodGYRO_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_pmod_bridge_0_0/PmodGYRO_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_quad_spi_0_0/PmodGYRO_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_quad_spi_0_0/PmodGYRO_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_quad_spi_0_0/PmodGYRO_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_quad_spi_0_0/PmodGYRO_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_gpio_0_0/PmodGYRO_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_gpio_0_0/PmodGYRO_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/src/PmodGYRO_axi_gpio_0_0/PmodGYRO_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_proc_sys_reset_0_0/design_gyro_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_proc_sys_reset_0_0/design_gyro_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_proc_sys_reset_0_0/design_gyro_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_0/design_gyro_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_0/design_gyro_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_0/design_gyro_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_dlmb_v10_2/design_gyro_dlmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_dlmb_v10_2/design_gyro_dlmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_ilmb_v10_2/design_gyro_ilmb_v10_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_ilmb_v10_2/design_gyro_ilmb_v10_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_dlmb_bram_if_cntlr_2/design_gyro_dlmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_ilmb_bram_if_cntlr_2/design_gyro_ilmb_bram_if_cntlr_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_lmb_bram_2/design_gyro_lmb_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_xbar_1/design_gyro_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_mdm_1_2/design_gyro_mdm_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_mdm_1_2/design_gyro_mdm_1_2_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_clk_wiz_1_0/design_gyro_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_clk_wiz_1_0/design_gyro_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_clk_wiz_1_0/design_gyro_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_rst_clk_wiz_1_100M_1/design_gyro_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_rst_clk_wiz_1_100M_1/design_gyro_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_rst_clk_wiz_1_100M_1/design_gyro_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_axi_uartlite_0_0/design_gyro_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_axi_uartlite_0_0/design_gyro_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/ip/design_gyro_axi_uartlite_0_0/design_gyro_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/sources_1/bd/design_gyro/design_gyro_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/constrs_1/new/nexys4ddr_gyro.xdc
set_property used_in_implementation false [get_files C:/Users/eliza/Documents/1_Local/ECE532_local/gyro_test/gyro_test.srcs/constrs_1/new/nexys4ddr_gyro.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_gyro_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_gyro_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_gyro_wrapper_utilization_synth.rpt -pb design_gyro_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
