# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys4ddr_gyro.xdc

# Block Designs: bd/design_gyro/design_gyro.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro || ORIG_REF_NAME==design_gyro} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_PmodGYRO_0_0/design_gyro_PmodGYRO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_PmodGYRO_0_0 || ORIG_REF_NAME==design_gyro_PmodGYRO_0_0} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_proc_sys_reset_0_0/design_gyro_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_proc_sys_reset_0_0 || ORIG_REF_NAME==design_gyro_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_microblaze_0_0/design_gyro_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_microblaze_0_0 || ORIG_REF_NAME==design_gyro_microblaze_0_0} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_dlmb_v10_2/design_gyro_dlmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_dlmb_v10_2 || ORIG_REF_NAME==design_gyro_dlmb_v10_2} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_ilmb_v10_2/design_gyro_ilmb_v10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_ilmb_v10_2 || ORIG_REF_NAME==design_gyro_ilmb_v10_2} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_dlmb_bram_if_cntlr_2/design_gyro_dlmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_gyro_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_ilmb_bram_if_cntlr_2/design_gyro_ilmb_bram_if_cntlr_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==design_gyro_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_lmb_bram_2/design_gyro_lmb_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_lmb_bram_2 || ORIG_REF_NAME==design_gyro_lmb_bram_2} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_xbar_1/design_gyro_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_xbar_1 || ORIG_REF_NAME==design_gyro_xbar_1} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_microblaze_0_axi_periph_1/design_gyro_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_microblaze_0_axi_periph_1 || ORIG_REF_NAME==design_gyro_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_microblaze_0_axi_intc_1/design_gyro_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_microblaze_0_axi_intc_1 || ORIG_REF_NAME==design_gyro_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_microblaze_0_xlconcat_1/design_gyro_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_microblaze_0_xlconcat_1 || ORIG_REF_NAME==design_gyro_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_mdm_1_2/design_gyro_mdm_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_mdm_1_2 || ORIG_REF_NAME==design_gyro_mdm_1_2} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_clk_wiz_1_0/design_gyro_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_clk_wiz_1_0 || ORIG_REF_NAME==design_gyro_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_rst_clk_wiz_1_100M_1/design_gyro_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_gyro_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_axi_uartlite_0_0/design_gyro_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_axi_uartlite_0_0 || ORIG_REF_NAME==design_gyro_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_gyro/ip/design_gyro_axi_quad_spi_0_0/design_gyro_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_gyro_axi_quad_spi_0_0 || ORIG_REF_NAME==design_gyro_axi_quad_spi_0_0} -quiet] -quiet

# XDC: bd/design_gyro/design_gyro_ooc.xdc
